import { ArrowRight, BookOpen, Cloud, Code2, Github, GraduationCap, Linkedin, Mail, Network, Sparkles, Workflow, Wrench } from 'lucide-react';

const linkedin = 'https://www.linkedin.com/in/amitesh-srivastava-b5b740105/';
const github = 'https://github.com/asrvstv5';
const dietmate = 'https://apps.apple.com/us/app/dietmate-app/id6503179053';
const medium1 = 'https://medium.com/@amitesh.s.sr/planning-an-app-a-detailed-guide-a366b180e220';
const medium2 = 'https://medium.com/@amitesh.s.sr/langchain-simplified-ad0c4b4d63e3';

const interests = [
  ['AI for Software Engineering', Sparkles], ['LLM / Agentic Software Engineering', Network], ['Developer Productivity & Tooling', Wrench],
  ['Distributed Systems & Cloud Infrastructure', Cloud], ['Software Reliability & Testing', Workflow], ['Human-AI Collaboration in Software Development', Sparkles]
] as const;

const projects = [
  { title: 'Copilot Plugin Management Platform', eyebrow: 'Microsoft · Power Automate', text: 'Led platform development for Microsoft Copilot plugin testing, enabling users to perform automation through Copilot’s chatbot and test Power Automate Connector Plugins.', tags: ['Power Automate', 'Copilot', 'REST APIs', 'Platform Engineering'] },
  { title: 'Horizon Avatar Editor', eyebrow: 'Meta · Full-Stack', text: 'Led development of the Horizon Avatar Editor Marketplace experience with React Native and GraphQL APIs, integrating recommendation and experimentation systems to improve personalization and engagement.', tags: ['React Native', 'TypeScript', 'GraphQL', 'Recommendations'] },
  { title: 'Live Playable In-line Ads', eyebrow: 'Meta · Family of Apps', text: 'Built backend APIs, in-game logging and interaction tracking, and deployment infrastructure for lightweight Horizon game experiences across Instagram, Facebook, and Horizon feeds.', tags: ['Backend APIs', 'Experimentation', 'Distributed Systems', 'Ads'] },
  { title: 'Dietmate', eyebrow: 'Independent · iOS App', text: 'Built a nutrition tracking application from scratch that uses AI-assisted food understanding to estimate calories and macronutrients, helping users understand and manage daily intake.', tags: ['SwiftUI', 'Python', 'Flask', 'MongoDB', 'AI'] }
];

export default function Home() {
  const personJsonLd = { '@context': 'https://schema.org', '@type': 'Person', name: 'Amitesh Srivastava', jobTitle: 'Software Engineer', url: 'https://amiteshsrivastava.com', sameAs: [linkedin, github], alumniOf: { '@type': 'CollegeOrUniversity', name: 'University of Illinois Urbana-Champaign' }, worksFor: { '@type': 'Organization', name: 'Meta' } };
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }} />
    <header className="nav"><div className="nav-inner"><a className="brand" href="#home">Amitesh Srivastava</a><nav>{['Home','About','Experience','Research','Projects','Writing','Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><div className="nav-social"><a href={linkedin} aria-label="LinkedIn"><Linkedin size={18}/></a><a href={github} aria-label="GitHub"><Github size={18}/></a><a href="mailto:amitesh.s.sr@gmail.com" aria-label="Email"><Mail size={18}/></a></div></div></header>
    <section id="home" className="hero"><div className="hero-copy"><h1>Amitesh Srivastava</h1><p className="role">Software Engineer&nbsp; @ &nbsp;Meta&nbsp; | &nbsp;Formerly Microsoft<br/>UIUC Computer Engineering Alumni</p><p className="lead">I build large-scale software systems at the intersection of AI, software engineering, and developer productivity. I’m passionate about applying cutting-edge technology to solve real-world problems and contributing to the broader research and engineering community.</p><div className="actions"><a className="button primary" href="#contact">Get in touch <ArrowRight size={15}/></a><a className="button secondary" href="/resume">View my resume <ArrowRight size={15}/></a></div><div className="identity-links"><a href={linkedin}><Linkedin size={15}/> LinkedIn</a><a href={github}><Github size={15}/> GitHub</a><span><GraduationCap size={15}/> Google Scholar</span><span><span className="orcid">iD</span> ORCID</span></div></div><div className="hero-art"><img src="/uiuc-quad.jpg" alt="University of Illinois Urbana-Champaign Quad at sunset" /></div></section>
    <section id="about" className="section about"><div><div className="section-label">01 · ABOUT</div><h2>About Me</h2><p>I’m a software engineer with 7+ years of experience at Meta and Microsoft, building and scaling products used by millions of people worldwide. My work spans backend infrastructure, distributed systems, AI-powered products, and developer tooling.</p><p>I’m also deeply interested in research at the intersection of AI and software engineering, and I’m actively looking for opportunities to contribute as a peer reviewer for journals, workshops, and conferences in this space.</p><a className="text-link" href="#contact">Learn more about my background <ArrowRight size={14}/></a></div><div className="interest-card"><h3>Research Interests</h3>{interests.map(([label, Icon]) => <div className="interest" key={label as string}><Icon size={17}/><span>{label as string}</span></div>)}</div></section>
    <section id="experience" className="section"><div className="section-heading"><div><div className="section-label">02 · EXPERIENCE</div><h2>Professional Experience</h2></div><a className="text-link" href="#experience">View full experience <ArrowRight size={14}/></a></div><div className="timeline"><article className="job"><div className="company-mark meta">∞</div><div className="job-main"><h3>Meta</h3><strong>Software Engineer</strong><p>Led development across Horizon and Meta’s Family of Apps, including playable advertising experiences, AI-powered game creation, Avatar Editor Marketplace, recommendation systems, and cloud-streamed game infrastructure.</p></div><div className="job-meta">May 2025 – Present<br/><span>New York, NY</span></div></article><article className="job"><div className="company-mark ms"><i></i><i></i><i></i><i></i></div><div className="job-main"><h3>Microsoft</h3><strong>Software Engineer II</strong><p>Built full-stack Power Platform and Copilot plugin infrastructure, cybersecurity tooling, GraphQL services, deployment pipelines, and network engineering systems.</p></div><div className="job-meta">May 2019 – Feb 2025<br/><span>Seattle, WA</span></div></article></div></section>
    <section id="research" className="section research"><div className="section-label">03 · RESEARCH</div><h2>Research</h2><div className="research-placeholder"><Sparkles size={20}/><div><h3>Research & Publications</h3><p>Peer-reviewed publications and formal research contributions are coming soon. Current interests include AI for software engineering, agentic systems, developer productivity, reliability, and human-AI collaboration.</p></div><span>Coming soon</span></div></section>
    <section id="projects" className="section"><div className="section-heading"><div><div className="section-label">04 · PROJECTS</div><h2>Featured Work</h2></div><a className="text-link" href="#projects">View all projects <ArrowRight size={14}/></a></div><div className="project-grid">{projects.map((p, i) => <article className="project" key={p.title}><div className={`project-visual v${i}`}><Code2 size={24}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="project-body"><div className="eyebrow">{p.eyebrow}</div><h3>{p.title}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div>{p.title === 'Dietmate' && <a href={dietmate} className="text-link">View on App Store <ArrowRight size={13}/></a>}</div></article>)}</div></section>
    <section id="writing" className="section"><div className="section-heading"><div><div className="section-label">05 · WRITING</div><h2>Writing & Talks</h2></div><a className="text-link" href={medium1}>View all writing <ArrowRight size={14}/></a></div><div className="writing-grid"><a className="writing" href={medium1}><BookOpen size={18}/><div><h3>Planning an App: A Detailed Guide</h3><p>Thoughts on taking an app idea from planning through implementation.</p></div><ArrowRight size={16}/></a><a className="writing" href={medium2}><BookOpen size={18}/><div><h3>LangChain Simplified</h3><p>An accessible exploration of LangChain and building LLM-powered applications.</p></div><ArrowRight size={16}/></a></div></section>
    <section id="contact" className="contact"><div><div className="section-label">06 · CONTACT</div><h2>Interested in collaborating?</h2><p>I’m always open to connecting with researchers, engineers, and builders working on exciting problems at the intersection of AI and software engineering.</p></div><a className="button primary" href="mailto:amitesh.s.sr@gmail.com">Get in touch <ArrowRight size={15}/></a></section>
    <footer><div><strong>Amitesh Srivastava</strong><p>Building a more capable and productive future through technology.</p></div><div className="footer-right"><a href="#home">Home</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#research">Research</a><a href="#projects">Projects</a><a href="#writing">Writing</a><a href="#contact">Contact</a><small>© 2026 Amitesh Srivastava. All rights reserved.</small></div></footer>
  </main>;
}
